import Head from 'next/head'
import Feature from '../components/Features'

import Navbar from '../components/Navbar'
import Main from './Main'



export default function Home() {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      
        
      </Head>

      <Navbar/>
      <Main/>
      
      <Feature/>


    
      
    </div>
  )
}
