import Head from "next/head";
import Feature from "../components/Features";
import Footer from "../components/Footer";

import Navbar from "../components/Navbar";
import Pricing from "../components/Pricing";
import UseCase from "../components/Usecase";
import Main from "../components/Main";

export default function Home() {
  return (


    
    <div className="overflow-hidden">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Main />
      <Feature />
      <UseCase />
      <Pricing />
      <Footer />
    </div>
  );
}
